import { execFileSync } from 'node:child_process';
import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';

// Read-only scan of repository inputs. Findings contain locations, never values.
const files = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], { encoding: 'utf8' }).split('\0').filter(Boolean);
const rules = {
  provenance: /(?:co-written with|written with)\s+cursor|generated by (?:an? )?(?:AI|ChatGPT|Copilot|Cursor)|AI assistant signature/i,
  secret: /(?:AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9]{30,}|sk-[A-Za-z0-9_-]{32,}|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----)/,
  machinePath: /(?:[A-Z]:\\Users\\|\/Users\/|\/home\/)[^\s'"`]+/,
  network: /\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|sendBeacon)\b|https?:\/\//,
  executableInput: /dangerouslySetInnerHTML|\.innerHTML\s*=|\beval\s*\(|new Function\s*\(/,
};
const inventory = [], findings = [];
for (const file of files) {
  const bytes = readFileSync(file);
  const binary = bytes.subarray(0,8192).includes(0) || /\.(png|jar)$/i.test(file);
  const record = { file, bytes: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex'), review: binary ? 'binary packaging inventory' : 'whole-file static scan' };
  if (/\.png$/i.test(file) && bytes.readUInt32BE(0) === 0x89504e47) { record.width = bytes.readUInt32BE(16); record.height = bytes.readUInt32BE(20); }
  inventory.push(record);
  if (binary) continue;
  const lines = bytes.toString('utf8').split(/\r?\n/);
  for(let i=0;i<lines.length;i++) for(const [rule,re] of Object.entries(rules)) {
    if(re.test(lines[i])) findings.push({file,line:i+1,rule});
  }
}
const lock = JSON.parse(readFileSync('package-lock.json','utf8'));
const licenses = {}, scripts = [], missingIntegrity = [], unusualSources = [];
for(const [name,pkg] of Object.entries(lock.packages)) {
  licenses[pkg.license ?? 'unspecified'] = (licenses[pkg.license ?? 'unspecified'] ?? 0)+1;
  if(name && pkg.resolved && !pkg.integrity) missingIntegrity.push(name);
  if(pkg.resolved && !pkg.resolved.startsWith('https://registry.npmjs.org/')) unusualSources.push(name);
  if(name && existsSync(`${name}/package.json`)) {
    const installed = JSON.parse(readFileSync(`${name}/package.json`,'utf8'));
    const lifecycle = Object.keys(installed.scripts ?? {}).filter(k => ['preinstall','install','postinstall','prepare'].includes(k));
    if(lifecycle.length) scripts.push({name, lifecycle});
  }
}
mkdirSync('.cache/audit',{recursive:true});
writeFileSync('.cache/audit/repository.json',JSON.stringify({inventory,findings,licenses,scripts,missingIntegrity,unusualSources},null,2));
console.log(JSON.stringify({files:inventory.length,binary:inventory.filter(i=>i.review.startsWith('binary')).length,findings: Object.fromEntries(Object.keys(rules).map(k=>[k,findings.filter(f=>f.rule===k).length])),licenses,scripts,missingIntegrity,unusualSources},null,2));
if(findings.some(f=>f.rule==='secret')) process.exitCode=1;
